"""Supervisor-facing task-plan content shared by the DOCX/PDF builders."""

TASKS = [
    ("איתור ושחזור לוג האינטראקציות מההרצה המקורית", "P0", {
        "מטרה": "לבדוק אם interaction_log.jsonl המקורי עדיין קיים לפני שינוי קוד או תשלום עבור הרצה חדשה.",
        "מה אני אבצע": "אחפש בכל ZIP, archive, תיקיית evaluation ו-artifact מקומי; אם אמצא, אחשב SHA-256, אמפה סוגי רשומות ותוויות model-call, ואבדוק אם ניתן לשחזר פלטים גולמיים ו-provenance עשירים יותר.",
        "המקור לזיהוי האוטומטי": "VEGO-AI/eval/eval_config.json (interaction_log) וכתיבת response_raw ב-llm_client.py.",
        "ה-Dataset": "הרצת Cheers/ParkWise המקורית וכל הארכיונים שסופקו.",
        "הפלט": "interaction-log recovery/availability report עם found/not found, hash ומצאי שדות.",
        "קריטריון השלמה": "מתועד מה נמצא ומה לא; הלוג יכול לשחזר רק קריאות שבוצעו בפועל ואינו יכול להכיל תשובות יועץ שמעולם לא נוצרו.",
        "מה נדרש ממני": "חיפוש, hash, inventory ותיעוד גבול השחזור.",
        "מה נדרש מאיריס וארנון": "רק אם לא אמצא בעצמי: להעביר את interaction_log.jsonl המקורי. ללא תיוג או בדיקה ידנית.",
        "מה חסר / מאתגר": "ייתכן שהקובץ לא נמסר או שלולאת תשובות ה-Q&A לא הופעלה; אין לצפות לשחזור answer confidence מקריאה שלא נוצרה.",
        "תלויות": "גישה לחבילות ולארכיונים המקומיים.",
        "הערכת זמן": "Ali: 0.5–1 שעה; API: אין עלות.",
    }),
    ("קיבוע מצב Q&A הקיים", "P0", {
        "מטרה": "לקבע את המצאי הקיים בלי לטעון טענת אי-מענה.",
        "מה אני אבצע": "אאמת 12 שאלות Agent 2 → Agent 1, 0 תשובות תואמות שנשמרו, היעדר confidence/evidence, והמסלולים הנתמכים-בקוד אך לא נצפו; אשתמש ב-ANSWER_NOT_PERSISTED.",
        "המקור לזיהוי האוטומטי": "agentB_best_guidelines.json, eval_state.json, היסטוריות lang/dom Q&A, orchestrator ו-hash manifest.",
        "ה-Dataset": "ucd_ch, ucd_pw, cd_ch, cd_pw; snapshot סופי ו-30 רשומות snapshot נפרדות.",
        "הפלט": "דוח observability קפוא עם מטריצת תקשורת, ספירות וגבול טענה.",
        "קריטריון השלמה": "לכל רשומה source hash; אין ניסוח המסיק שהתרחשה אי-מענה בזמן הריצה.",
        "מה נדרש ממני": "קיבוע דוח וטרמינולוגיה.",
        "מה נדרש מאיריס וארנון": "לא נדרש דבר.",
        "מה חסר / מאתגר": "אין episode מלא או תשובה שמורה ב-artifact הנוכחי.",
        "תלויות": "תוצאת משימה 1 וה-artifacts הקפואים.",
        "הערכת זמן": "Ali: 0.5–1 שעה; מכונה: פחות מ-5 דקות.",
    }),
    ("הגדרת אירוע Q&A מלא", "P0", {
        "מטרה": "להגדיר יחידת observability מינימלית שניתנת לשחזור ולבדיקה.",
        "מה אני אבצע": "אקבע schema versioned הכולל question ID, source/target agent, stage, question, answer, confidence/evidence, episode, round, follow-up, convergence/termination ו-context.",
        "המקור לזיהוי האוטומטי": "runtime state, qa_registry.py, state.py ו-contract האירוע.",
        "ה-Dataset": "fixtures בטוחים ללא טקסטי סטודנטים.",
        "הפלט": "מפרט qa-communication-event-v1 ו-validator.",
        "קריטריון השלמה": "כל שדה חובה מוגדר עם provenance ו-nullable policy; confidence נשאר נפרד מ-mapping certainty ומ-Agent 4 confidence.",
        "מה נדרש ממני": "הגדרת חוזה האירוע ובדיקת schema.",
        "מה נדרש מאיריס וארנון": "לא נדרש דבר.",
        "מה חסר / מאתגר": "חלק מהשדות אינם קיימים ב-runtime הנוכחי ויישארו unavailable עד instrumentation.",
        "תלויות": "משימות 1–2 והגבלות privacy/governance.",
        "הערכת זמן": "Ali: 1–2 שעות; מכונה: פחות מ-10 דקות.",
    }),
    ("instrumentation פסיבי של Q&A", "P0", {
        "מטרה": "לשמור פרקי Q&A בלי לשנות prompts, החלטות או התנהגות סוכנים.",
        "מה אני אבצע": "אוסיף כתיבה פסיבית של אירועי v1 בנקודות יצירה, השבה וסיום; אוסיף hash ומניפסט; לא אוסיף labels ולא אכוון detector לפי תוצאות.",
        "המקור לזיהוי האוטומטי": "orchestrator.py, qa_registry.py, state.py ו-event writer.",
        "ה-Dataset": "fixtures והרצה מקומית מבוקרת.",
        "הפלט": "event records חתומים ומקושרים ל-run manifest.",
        "קריטריון השלמה": "כל episode מכיל שדות חובה והשינוי אינו משנה את פלט ה-baseline.",
        "מה נדרש ממני": "מימוש instrumentation ובדיקות unit.",
        "מה נדרש מאיריס וארנון": "לא נדרש דבר, אלא אם governance מחייב אישור לשינוי runtime.",
        "מה חסר / מאתגר": "artifact volume, אי-דטרמיניזם וסיכון לשינוי עקיף; לכן השינוי passive בלבד.",
        "תלויות": "משימה 3 ואישור טכני לשינוי instrumentation בלבד.",
        "הערכת זמן": "Ali: 4–6 שעות; בדיקות: 15–30 דקות.",
    }),
    ("אימות instrumentation ושימור baseline", "P0", {
        "מטרה": "להראות שהאירועים נשמרים ושפלט VEGO-AI לא השתנה.",
        "מה אני אבצע": "אריץ unit/integration tests, schema validation, mandatory-field coverage, baseline hash comparison ושתי ריצות זהות על fixture/controlled run.",
        "המקור לזיהוי האוטומטי": "schema, manifests, canonical JSON hashes ו-baseline diff.",
        "ה-Dataset": "fixture בטוח והרצה מבוקרת מינימלית.",
        "הפלט": "verification receipt עם pass/fail, coverage ו-hash comparison.",
        "קריטריון השלמה": "אין שדה חובה חסר; אותה קלט/גרסה מפיקה אותם artifacts קנוניים; אין שינוי baseline.",
        "מה נדרש ממני": "כתיבת והרצת בדיקות ותיעוד חריגות.",
        "מה נדרש מאיריס וארנון": "לא נדרש דבר.",
        "מה חסר / מאתגר": "ריצה מול API כללי אינה בהכרח דטרמיניסטית; ההוכחה תוגבל ל-fixture ול-controlled run.",
        "תלויות": "משימה 4.",
        "הערכת זמן": "Ali: 2–3 שעות; ריצה: 15–45 דקות.",
    }),
    ("הרצה מבוקרת של setting אחד", "P1", {
        "מטרה": "להוכיח שה-instrumentation יוצר episodes מלאים לפני הרחבה לארבעת ה-settings.",
        "מה אני אבצע": "אבחר setting יחיד רק לאחר בדיקת input availability, אתעד את סיבת הבחירה, אפעיל dry-run והרצה מבוקרת, ואמדוד call count, runtime, failures ועלות API.",
        "המקור לזיהוי האוטומטי": "runtime logs, run manifest ואירועי qa-communication-event-v1.",
        "ה-Dataset": "Cheers או ParkWise עם UCD או CD, לפי ה-setting הזמין; לא מובטחת הרצת כל ארבעת ה-settings בשלב הראשון.",
        "הפלט": "corpus Q&A חתום, דוח כיסוי, call/runtime/cost receipt והחלטה אם להרחיב.",
        "קריטריון השלמה": "controlled run אחד מתועד; הרחבה מותנית בהצלחת completeness של ה-one-setting run.",
        "מה נדרש ממני": "בדיקת inputs, בחירת setting, dry-run, הרצה ותיעוד.",
        "מה נדרש מאיריס וארנון": "רק אם אין חלופה מקומית ונדרשת עלות: לאשר הרצה מבוקרת אחת ועלות API אפשרית.",
        "מה חסר / מאתגר": "inputs חסרים, עלות, אי-דטרמיניזם וזמן ריצה; אין להבטיח corpus מלא מראש.",
        "תלויות": "משימות 4–5, inputs והרשאות runtime.",
        "הערכת זמן": "Ali: 2–4 שעות; machine/API: כ-1–6 שעות לפי setting ועלות.",
    }),
    ("חילוץ אותות תקשורת אוטומטיים", "P1", {
        "מטרה": "לגזור רק אותות escalation שניתנים למדידה מן ה-corpus המועשר.",
        "מה אני אבצע": "אחשב confidence נמוך/בינוני, ANSWER_NOT_PERSISTED, evidence חסר, repeated question, follow-up, multiple rounds, non-convergence, MAX_QA_ROUNDS ו-high question count; mapping certainty ו-Agent 4 confidence יישארו context נפרד.",
        "המקור לזיהוי האוטומטי": "event fields, episode history ו-termination record.",
        "ה-Dataset": "corpus ממשימה 6; snapshot קיים ישמש sanity check בלבד.",
        "הפלט": "feature table קנונית עם source field, rule, availability, count ו-limitation.",
        "קריטריון השלמה": "שום proxy אינו מסומן כ-ground truth וכל unavailable נשמר כ-unavailable.",
        "מה נדרש ממני": "מימוש features ובדיקות determinism.",
        "מה נדרש מאיריס וארנון": "לא נדרש דבר.",
        "מה חסר / מאתגר": "אות שלא נשמר אינו ניתן לשחזור אמין בדיעבד.",
        "תלויות": "משימה 6.",
        "הערכת זמן": "Ali: 2–3 שעות; ריצה: פחות מ-10 דקות.",
    }),
    ("Detector שקוף וניתוח תיאורי", "P1", {
        "מטרה": "להפיק ALERT/NO ALERT וסטטיסטיקה תיאורית ללא machine learning או labels.",
        "מה אני אבצע": "אבנה rule-based detector עם reason codes, אריץ אותו על אותה טבלת episodes, ואדווח episodes, alert counts/rates, agent/stage/target, signals, confidence, ANSWER_NOT_PERSISTED, rounds/follow-up ו-repeatability.",
        "המקור לזיהוי האוטומטי": "feature table, detector manifest ו-run manifest.",
        "ה-Dataset": "corpus המאומת ממשימה 6.",
        "הפלט": "event-level decisions, descriptive-results JSON/CSV, תרשים ו-report קנוני.",
        "קריטריון השלמה": "כל decision מקושר ל-feature ול-event ID; אותה קלט/גרסה/seed מפיקה אותו hash.",
        "מה נדרש ממני": "rules, versioning, analysis ו-QA מספרי.",
        "מה נדרש מאיריס וארנון": "לא נדרש דבר.",
        "מה חסר / מאתגר": "בהיעדר מקור ייחוס עצמאי וללא תיוג ידני בשלב הנוכחי, ניתן למדוד באופן מלא את מספר ההתראות, התפלגותן והאותות שהפעילו אותן, אך לא ניתן לקבוע באופן אמפירי בשלב זה אילו מהן True/False.",
        "תלויות": "משימה 7; אין tuning לפי labels.",
        "הערכת זמן": "Ali: 2–3 שעות; ריצה: פחות מ-15 דקות.",
    }),
]
